public final class Database { // 2.1.0

    Entry[] a;

    public Database() {
        this.a = new Entry[600];
        a[0] = new Entry("./res/intro_1.png", "WELCOME TO FANTASY CAMPERS - AN ADVENTURE GAME!", new String[]{"Click here to Continue"}, new int[]{1}); // 1.0.0, 4.0.0, 8.0.0, 8.1.0
        a[1] = new Entry("./res/Plain.png", "Unlike many other stories, this one begins—and ENDS—with you and your choices!", new String[]{"->"}, new int[]{2});
        a[2] = new Entry("./res/Plain.png", "How does that work, you ask? Great question! Beginning on the next screen, you'll be immersed into a magical tale that involves saving a princess, and much more!", new String[]{"->"}, new int[]{3});
        a[3] = new Entry("./res/Plain.png", "The difference between this story and many like it is that YOU are in control. ",  new String[]{"->"}, new int[]{4});
        a[4] = new Entry("./res/Plain.png", "You will embark on a journey that requires you to make choices at every turn. Some of these choices may lead to perilous consequences, while other choices may make you the hero of your own story...", new String[]{"->"}, new int[]{5});
        a[5] = new Entry("./res/Plain.png", "Are you ready for an adventure?", new String[]{"Yes! Let's do this!", "No, I'm Scared..."}, new int[]{500,6});
        a[500] = new Entry("./res/begin_play.png", "", new String[]{"Click here to Continue"}, new int[]{7});
        a[6] = new Entry("./res/game_over.png", "THE END\n\"A man that flies from his fear may find that he has only taken a short cut to meet it.\"\n" + "-J.R.R. Tolkien\n", new String[]{"Start Over"}, new int[]{0}); // 6.0.0
        a[7] = new Entry("./res/begin_play.png", "The sun brightly shines on the village of Clearborrow, while the townspeople stroll about in the marketplace and talk happily amongst themselves...", new String[]{"->"}, new int[]{8});
        a[8] = new Entry("./res/begin_play.png", "As you pass through, taking in the sights and sounds, you observe your surroundings. One vendor is selling fresh brown bread, while another vendor is selling cured bacon and ale. ", new String[]{"->"}, new int[]{9});
        a[9] = new Entry("./res/begin_play.png", "Off in the distance, beyond the village, you see Clearborrow castle, where Princess Seraphina is waiting with her father, the King of Clearborrow. ", new String[]{"Proceed to the castle and meet the King","The castle looks kind of far, maybe this was a bad idea..."}, new int[]{501,6}); // 3.0.0, 5.0.0, 10.0.0
        a[501] = new Entry("./res/at_the_castle.png", "", new String[]{"Click here to Continue"}, new int[]{10});
        a[10] = new Entry("./res/at_the_castle.png", "You make your way to the castle, and as you enter the court, you’re greeted by the King himself, who exclaims loudly:", new String[]{"->"}, new int[]{11});
        a[11] = new Entry("./res/at_the_castle.png", "\"Hello good Nobelman. I tremendously appreciate your bravery in offering to escort my daughter, the Princess of Clearborrow, to the Kingdom of Woodness in order to meet the Prince of Woodness so that they may marry.", new String[]{"->"}, new int[]{12});
        a[12] = new Entry("./res/at_the_castle.png", "I have been told many tales of your bravery, as well as your courage.", new String[]{"->"}, new int[]{13});
        a[13] = new Entry("./res/at_the_castle.png", "Do you accept my offer of 50 shillings and the title of Count of Clearborrow in exchange for guaranteeing my daughter's safe passage to Woodness?\"", new String[]{"Accept the King's Offer", "Negotiate for 100 shillings", "Slap the King. Why Not? Let's Get Crazy!"}, new int[]{19,21,14});
        a[14] = new Entry("./res/slap_king.png", "", new String[]{"->"}, new int[]{15});
        a[15] = new Entry("./res/slap_king.png", "Upon slapping the King, you were arrested by the knights and imprisoned in the Royal Dungeon for a sentence of 20 years.", new String[]{"->"}, new int[]{16});
        a[16] = new Entry("./res/slap_king.png", "When the Prince (who never liked his father) took power, he took mercy on you, commuting your sentence to 5 years total.", new String[]{"->"}, new int[]{17});
        a[17] = new Entry("./res/slap_king.png", "After leaving prison you became a farmer and were never remembered in history for saving the Princess or anything heroic.", new String[]{"->"}, new int[]{18});
        a[18] = new Entry("./res/slap_king.png", "\"But man is not made for defeat. A man can be destroyed, but not defeated...\"\n-Ernest Hemingway\n", new String[]{"Start Over", "Meet the King Again"}, new int[]{0,10}); // 6.0.0, 7.0.0
        a[19] = new Entry("./res/journey_begins.png", "\"I thank you for your bravery and willingness to escort the Princess to Woodness. You are indeed a brave and courageous soul.", new String[]{"->"}, new int[]{20});
        a[20] = new Entry("./res/journey_begins.png", "I would also like to introduce you to some trusted members of my court - my best Knight and my loyal Mage. I would like them to accompany you to Woodness with the Princess. Will you accept this request?\"", new String[]{"Travel with the Knight & Mage", "Refuse and Go Alone"}, new int[]{27,502}); // 3.0.0, 5.0.0
        a[21] = new Entry("./res/journey_begins_shillings.png", "\"Young Nobleman, you are a steadfast negotiator, and as the King—I can respect that.", new String[]{"->"}, new int[]{22});
        a[22] = new Entry("./res/journey_begins_shillings.png", "Henceforth and forever more, I will agree to your offer of 100 shillings, but not a single shilling more.", new String[]{"->"}, new int[]{20});
        a[502] = new Entry("./res/go_alone.png", "", new String[]{"Click here to Continue"}, new int[]{23});
        a[23] = new Entry("./res/go_alone.png", "Because you did not accept help from the Knight and Mage, you were ambushed shortly after leaving the village.", new String[]{"->"}, new int[]{24});
        a[24] = new Entry("./res/go_alone.png", "You died courageously, fighting to save the Princess and escape, but your efforts were not enough. ", new String[]{"->"}, new int[]{25});
        a[25] = new Entry("./res/go_alone.png", "The Princess was captured by a band of thieves and later recovered by the King’s nights.\n However, by this time, the Prince was already married.", new String[]{"->"}, new int[]{26});
        a[26] = new Entry("./res/go_alone.png", "\"It is not in the stars to hold our destiny but in ourselves.\"\n-William Shakespeare", new String[]{"Start Over", "Meet the King Again"}, new int[]{0,10}); // 6.0.0, 7.0.0
        a[27] = new Entry("./res/supplies.png", "Before you leave the village of Woodness, some of the King's assistants offer to furnish you with supplies and food to last the duration of your trip.", new String[]{"->"}, new int[]{28});
        a[28] = new Entry("./res/supplies.png", "While you realize that supplies would be helpful, there are also various towns along the way where you could stop and obtain supplies.", new String[]{"->"}, new int[]{29});
        a[29] = new Entry("./res/supplies.png", "You also have a limited capacity for carrying supplies, but do realize they could be beneficial.\n What do you do?", new String[]{"Take the Supplies - It's Good to Have Them Just in Case", "Don't Take the Supplies – You Can Get Them Somewhere Else"}, new int[]{32,30});
        a[30] = new Entry("./res/game_over.png", "Because you left without supplies, you did not make it. \n There were no towns along the way close enough to get food or medicine, putting everyone in an unrecoverable, perilous situation.\n Because of your foolishness and presumptions, the entire group perished.", new String[]{"->"}, new int[]{31});
        a[31] = new Entry("./res/game_over.png", "\"Talk sense to a fool and he calls you foolish.\"\n-William Shakespeare", new String[]{"Go back to Supplies Screen", "Start Over"}, new int[]{27,0});
        a[32] = new Entry("./res/storm.png", "Armed with your supplies you set out for Woodness. As you are on the way, you encounter a terrible storm. Members of the group argue on what to do next...", new String[]{"->"}, new int[]{33});
        a[33] = new Entry("./res/storm.png", "\"I believe that we should turn back for Clearborrow before this gets worse!\" said the Mage.\n\"I say we should press on and get through this!\" said the Knight.\n\"I think we should stay in a local inn for the night...\" said the Princess.\r\nYou realize that these are all viable options. Who do you listen to?", new String[]{"The Knight", "The Mage","The Princess"}, new int[]{34,37,40});
        a[34] = new Entry("./res/game_over.png", "While the Mage is wise and has many powers, he can’t tell the future.\nUnfortunately turning back for Clearborrow cost you weeks of time on your journey.",  new String[]{"->"}, new int[]{35});
        a[35] = new Entry("./res/game_over.png", "Because the Princess did not arrive on time, the Prince stayed in battle longer and was captured by the enemy and never found again.\nThe Mage is a wise companion, but not necessarily the best navigator.",  new String[]{"->"}, new int[]{36});
        a[36] = new Entry("./res/game_over.png", "\"Wrong does not cease to be wrong because the majority share in it.\"\n-Leo Tolstoy",  new String[]{"Go back to storm screen", "Start over"}, new int[]{32,0});
        a[37] = new Entry("./res/game_over.png", "While the Knight may be the bravest of the group, he is definitely not the wisest...\nPressing on through the storm cause everyone to become wet, and the group to lost their bearings. ",  new String[]{"->"}, new int[]{38});
        a[38] = new Entry("./res/game_over.png", "The group was eventually caught in a mudslide and fell into the river, with no one ever being seen again.",  new String[]{"->"}, new int[]{39});
        a[39] = new Entry("./res/game_over.png", "\"I have not failed. I’ve just found 10,000 ways that won’t work.\"\n-Thomas Edison",  new String[]{"Go back to storm screen", "Start over"}, new int[]{32,0});
        a[40] = new Entry("./res/encounter_travelers.png", "Taking the good advice from the Princess to seek refuge in the Village of Greyhaven for a night, the group was able to rest, recoup, and avoid the storm.\nAfter a solid night’s sleep, the group set back out on their way to Woodness. ",  new String[]{"->"}, new int[]{41});
        a[41] = new Entry("./res/encounter_travelers.png", "As the sun began to set again, a small group of strangers appeared on the trailside. They seemed to be distressed travelers, and the Princess suggested that they may be in need of some help. ",  new String[]{"->"}, new int[]{42});
        a[42] = new Entry("./res/encounter_travelers.png", "Members of your group debate among themselves about who to send to make contact with the distressed travelers. Everyone agrees that it’s too dangerous for the Princess to go by herself, so that leaves you, the Mage, or the Knight as options to walk forward and make first contact.",  new String[]{"->"}, new int[]{43});
        a[43] = new Entry("./res/encounter_travelers.png", "Because you’re the leader, the choice is up to you. Who do you send to contact the group?",  new String[]{"Go Yourself", "Send the Mage","Send the Knight"}, new int[]{99,99,99});
    }

}