public final class Database { // 2.1.0

    Entry[] a;

    public Database() {
        this.a = new Entry[600];
        a[0] = new Entry("./res/intro_1.png", "       WELCOME TO FANTASY CAMPERS - AN ADVENTURE GAME!", new String[]{"Click here to Continue"}, new int[]{1}); // 1.0.0, 4.0.0, 8.0.0, 8.1.0
        a[1] = new Entry("./res/Plain.png", "Unlike many other stories, this one begins—and ENDS—with you and your choices!", new String[]{"Click here to Continue"}, new int[]{2});
        a[2] = new Entry("./res/Plain.png", "How does that work, you ask? Great question! Beginning on the next screen, you'll be immersed into a magical tale that involves saving a princess, and much more!", new String[]{"Click here to Continue"}, new int[]{3});
        a[3] = new Entry("./res/Plain.png", "The difference between this story and many like it is that YOU are in control. ",  new String[]{"Click here to Continue"}, new int[]{4});
        a[4] = new Entry("./res/Plain.png", "You will embark on a journey that requires you to make choices at every turn. Some of these choices may lead to perilous consequences, while other choices may make you the hero of your own story...", new String[]{"Click here to Continue"}, new int[]{5});
        a[5] = new Entry("./res/Plain.png", "Are you ready for an adventure?", new String[]{"Yes! Let's do this!", "No, I'm Scared..."}, new int[]{500,6});
        a[500] = new Entry("./res/begin_play.png", "", new String[]{"Click here to Continue"}, new int[]{7});
        a[6] = new Entry("./res/game_over.png", "THE END\n\"A man that flies from his fear may find that he has only taken a short cut to meet it.\"\n" + "-J.R.R. Tolkien\n", new String[]{"Start Over"}, new int[]{0}); // 6.0.0
        a[7] = new Entry("./res/begin_play.png", "The sun brightly shines on the village of Clearborrow, while the townspeople stroll about in the marketplace and talk happily amongst themselves...", new String[]{"Click here to Continue"}, new int[]{8});
        a[8] = new Entry("./res/begin_play.png", "As you pass through, taking in the sights and sounds, you observe your surroundings. One vendor is selling fresh brown bread, while another vendor is selling cured bacon and ale. ", new String[]{"Click here to Continue"}, new int[]{9});
        a[9] = new Entry("./res/begin_play.png", "Off in the distance, beyond the village, you see Clearborrow castle, where Princess Seraphina is waiting with her father, the King of Clearborrow. ", new String[]{"Proceed to the castle and meet the King","The castle looks kind of far, maybe this was a bad idea..."}, new int[]{501,6}); // 3.0.0, 5.0.0, 10.0.0
        a[501] = new Entry("./res/at_the_castle.png", "", new String[]{"Click here to Continue"}, new int[]{10});
        a[10] = new Entry("./res/at_the_castle.png", "You make your way to the castle, and as you enter the court, you're greeted by the King himself, who exclaims loudly:", new String[]{"Click here to Continue"}, new int[]{11});
        a[11] = new Entry("./res/at_the_castle.png", "\"Hello good Nobelman. I tremendously appreciate your bravery in offering to escort my daughter, the Princess of Clearborrow, to the Kingdom of Woodness in order to meet the Prince of Woodness so that they may marry.", new String[]{"Click here to Continue"}, new int[]{12});
        a[12] = new Entry("./res/at_the_castle.png", "I have been told many tales of your bravery, as well as your courage.", new String[]{"Click here to Continue"}, new int[]{13});
        a[13] = new Entry("./res/at_the_castle.png", "Do you accept my offer of 50 shillings and the title of Count of Clearborrow in exchange for guaranteeing my daughter's safe passage to Woodness?\"", new String[]{"Accept the King's Offer", "Negotiate for 100 shillings", "Slap the King. Why Not? Let's Get Crazy!"}, new int[]{19,21,14});
        a[14] = new Entry("./res/slap_king.png", "", new String[]{"Click here to Continue"}, new int[]{15});
        a[15] = new Entry("./res/slap_king.png", "Upon slapping the King, you were arrested by the knights and imprisoned in the Royal Dungeon for a sentence of 20 years.", new String[]{"Click here to Continue"}, new int[]{16});
        a[16] = new Entry("./res/slap_king.png", "When the Prince (who never liked his father) took power, he took mercy on you, commuting your sentence to 5 years total.", new String[]{"Click here to Continue"}, new int[]{17});
        a[17] = new Entry("./res/slap_king.png", "After leaving prison you became a farmer and were never remembered in history for saving the Princess or anything heroic.", new String[]{"Click here to Continue"}, new int[]{18});
        a[18] = new Entry("./res/slap_king.png", "\"But man is not made for defeat. A man can be destroyed, but not defeated...\"\n-Ernest Hemingway\n", new String[]{"Start Over", "Meet the King Again"}, new int[]{0,10}); // 6.0.0, 7.0.0
        a[19] = new Entry("./res/journey_begins.png", "\"I thank you for your bravery and willingness to escort the Princess to Woodness. You are indeed a brave and courageous soul.", new String[]{"Click here to Continue"}, new int[]{20});
        a[20] = new Entry("./res/journey_begins.png", "I would also like to introduce you to some trusted members of my court - my best Knight and my loyal Mage. I would like them to accompany you to Woodness with the Princess. Will you accept this request?\"", new String[]{"Travel with the Knight & Mage", "Refuse and Go Alone"}, new int[]{27,502}); // 3.0.0, 5.0.0
        a[21] = new Entry("./res/journey_begins_shillings.png", "\"Young Nobleman, you are a steadfast negotiator, and as the King—I can respect that.", new String[]{"Click here to Continue"}, new int[]{22});
        a[22] = new Entry("./res/journey_begins_shillings.png", "Henceforth and forever more, I will agree to your offer of 100 shillings, but not a single shilling more.", new String[]{"Click here to Continue"}, new int[]{20});
        a[502] = new Entry("./res/go_alone.png", "", new String[]{"Click here to Continue"}, new int[]{23});
        a[23] = new Entry("./res/go_alone.png", "Because you did not accept help from the Knight and Mage, you were ambushed shortly after leaving the village.", new String[]{"Click here to Continue"}, new int[]{24});
        a[24] = new Entry("./res/go_alone.png", "You died courageously, fighting to save the Princess and escape, but your efforts were not enough. ", new String[]{"Click here to Continue"}, new int[]{25});
        a[25] = new Entry("./res/go_alone.png", "The Princess was captured by a band of thieves and later recovered by the King's nights.\n However, by this time, the Prince was already married.", new String[]{"Click here to Continue"}, new int[]{26});
        a[26] = new Entry("./res/go_alone.png", "\"It is not in the stars to hold our destiny but in ourselves.\"\n-William Shakespeare", new String[]{"Start Over", "Meet the King Again"}, new int[]{0,10}); // 6.0.0, 7.0.0
        a[27] = new Entry("./res/supplies.png", "Before you leave the village of Woodness, some of the King's assistants offer to furnish you with supplies and food to last the duration of your trip.", new String[]{"Click here to Continue"}, new int[]{28});
        a[28] = new Entry("./res/supplies.png", "While you realize that supplies would be helpful, there are also various towns along the way where you could stop and obtain supplies.", new String[]{"Click here to Continue"}, new int[]{29});
        a[29] = new Entry("./res/supplies.png", "You also have a limited capacity for carrying supplies, but do realize they could be beneficial.\n What do you do?", new String[]{"Take the Supplies - It's Good to Have Them Just in Case", "Don't Take the Supplies – You Can Get Them Somewhere Else"}, new int[]{32,30});
        a[30] = new Entry("./res/game_over.png", "Because you left without supplies, you did not make it. \n There were no towns along the way close enough to get food or medicine, putting everyone in an unrecoverable, perilous situation.\n Because of your foolishness and presumptions, the entire group perished.", new String[]{"Click here to Continue"}, new int[]{31});
        a[31] = new Entry("./res/game_over.png", "\"Talk sense to a fool and he calls you foolish.\"\n-William Shakespeare", new String[]{"Go back to Supplies Screen", "Start Over"}, new int[]{27,0});
        a[32] = new Entry("./res/storm.png", "Armed with your supplies you set out for Woodness. As you are on the way, you encounter a terrible storm. Members of the group argue on what to do next...", new String[]{"Click here to Continue"}, new int[]{33});
        a[33] = new Entry("./res/storm.png", "\"I believe that we should turn back for Clearborrow before this gets worse!\" said the Mage.\n\"I say we should press on and get through this!\" said the Knight.\n\"I think we should stay in a local inn for the night...\" said the Princess.\r\nYou realize that these are all viable options. Who do you listen to?", new String[]{"The Mage","The Knight","The Princess"}, new int[]{34,37,40});
        a[34] = new Entry("./res/game_over.png", "While the Mage is wise and has many powers, he can't tell the future.\nUnfortunately turning back for Clearborrow cost you weeks of time on your journey.",  new String[]{"Click here to Continue"}, new int[]{35});
        a[35] = new Entry("./res/game_over.png", "Because the Princess did not arrive on time, the Prince stayed in battle longer and was captured by the enemy and never found again.\nThe Mage is a wise companion, but not necessarily the best navigator.",  new String[]{"Click here to Continue"}, new int[]{36});
        a[36] = new Entry("./res/game_over.png", "\"Wrong does not cease to be wrong because the majority share in it.\"\n-Leo Tolstoy",  new String[]{"Go back to storm screen", "Start over"}, new int[]{32,0});
        a[37] = new Entry("./res/game_over.png", "While the Knight may be the bravest of the group, he is definitely not the wisest...\nPressing on through the storm cause everyone to become wet, and the group to lost their bearings. ",  new String[]{"Click here to Continue"}, new int[]{38});
        a[38] = new Entry("./res/game_over.png", "The group was eventually caught in a mudslide and fell into the river, with no one ever being seen again.",  new String[]{"Click here to Continue"}, new int[]{39});
        a[39] = new Entry("./res/game_over.png", "\"I have not failed. I've just found 10,000 ways that won't work.\"\n-Thomas Edison",  new String[]{"Go back to storm screen", "Start over"}, new int[]{32,0});
        a[40] = new Entry("./res/encounter_travelers.png", "Taking the good advice from the Princess to seek refuge in the Village of Greyhaven for a night, the group was able to rest, recoup, and avoid the storm.\nAfter a solid night's sleep, the group set back out on their way to Woodness. ",  new String[]{"Click here to Continue"}, new int[]{41});
        a[41] = new Entry("./res/encounter_travelers.png", "As the sun began to set again, a small group of strangers appeared on the trailside. They seemed to be distressed travelers, and the Princess suggested that they may be in need of some help. ",  new String[]{"Click here to Continue"}, new int[]{42});
        a[42] = new Entry("./res/encounter_travelers.png", "Members of your group debate among themselves about who to send to make contact with the distressed travelers. Everyone agrees that it's too dangerous for the Princess to go by herself, so that leaves you, the Mage, or the Knight as options to walk forward and make first contact.",  new String[]{"Click here to Continue"}, new int[]{43});
        a[43] = new Entry("./res/encounter_travelers.png", "Because you're the leader, the choice is up to you. Who do you send to contact the group?",  new String[]{"Go Yourself", "Send the Mage","Send the Knight"}, new int[]{99,44,47});
        a[44] = new Entry("./res/go_alone.png", "Although he's very magical, the Mage is not a fighter and was overwhelmed by the travelers—who turned out to be a band of thieves posing as distressed travelers in need.\nDuring the battle to defeat them, you and the Knight were both killed, and the Mage and Princess were taken hostage. ",  new String[]{"Click here to Continue"}, new int[]{45});
        a[45] = new Entry("./res/go_alone.png", "Eventually, the Mage and Princess were able to escape their captors and return to Clearborrow. \nHowever, this was not in time for the Princess to marry the Prince, as he married someone else that year. ",  new String[]{"Click here to Continue"}, new int[]{46});
        a[46] = new Entry("./res/go_alone.png", "\"Success is not final, failure is not fatal: it is the courage to continue that counts.\"\n-Winston Churchill",  new String[]{"Encounter Travellers again", "Start Over"}, new int[]{40,0});
        a[47] = new Entry("./res/knight_killed.png", "As the Knight approached the group of distressed travelers, he immediately realized something was terribly wrong...",  new String[]{"Click here to Continue"}, new int[]{48});
        a[48] = new Entry("./res/knight_killed.png", "The travelers, who turned out to be thieves, ambushed the Knight and he was killed battling them so the rest of the group could get away.\nYou, the Mage, and the Princess managed to get away and hide in the woods. ",  new String[]{"Click here to Continue"}, new int[]{49});
        a[49] = new Entry("./res/knight_killed.png", "The Mage says he can perform a time spell that allows you to go back in time to the moment before you chose to send the Knight. Or, you can go on without the Knight. What's your next move?",  new String[]{"Go On Without the Knight", "Go Back in Time"}, new int[]{59,40});
        a[50] = new Entry("./res/meets_rogue.png", "As you encounter the group of travelers, they introduce themselves—there are three people...",  new String[]{"Click here to Continue"}, new int[]{51});
        a[51] = new Entry("./res/meets_rogue.png", "A husband and wife who are local townspeople from Greyhaven, and a third person, a Rogue who escaped from the local town prison. She claims to be innocent, and to have been falsely convicted of her crime, although she will not tell you what this crime was.",  new String[]{"Click here to Continue"}, new int[]{52});
        a[52] = new Entry("./res/meets_rogue.png", "The Rogue asks if she can follow along with you to Woodness. She claims she is meeting people there who can prove her innocence. The husband and wife say that she caused them no trouble thus far.",  new String[]{"Click here to Continue"}, new int[]{53});
        a[53] = new Entry("./res/meets_rogue.png", "Do you let the Rogue come along with your party to Woodness? ",  new String[]{"No, She Might Be Trouble", "Yes, She Seems Harmless"}, new int[]{54,503});
        a[54] = new Entry("./res/rest_no_rogue.png", "",  new String[]{"Click here to continue"}, new int[]{55});
        a[55] = new Entry("./res/rest_no_rogue.png", "As the group is getting tired, you decide that it's a good idea to set up a camp just outside the town of Ironshade.\nBecause this area is known to be somewhat dangerous, you decide that someone must stay up and keep watch at all times. ",  new String[]{"Click here to Continue"}, new int[]{56});
        a[56] = new Entry("./res/rest_no_rogue.png", "So everyone can sleep, you also decide that this will be done in shifts. The question is, who takes the first watch shift?",  new String[]{"You", "The Knight", "The Mage"}, new int[]{65,68,70});
        a[503] = new Entry("./res/rest_no_rogue.png", "",  new String[]{"Click here to continue"}, new int[]{57});
        a[57] = new Entry("./res/rest_rogue.png", "As the group is getting tired, you decide that it's a good idea to set up a camp just outside the town of Ironshade.\nBecause this area is known to be somewhat dangerous, you decide that someone must stay up and keep watch at all times. ",  new String[]{"Click here to Continue"}, new int[]{58});
        a[58] = new Entry("./res/rest_rogue.png", "So everyone can sleep, you also decide that this will be done in shifts. The question is, who takes the first watch shift?",  new String[]{"You", "The Knight", "The Mage", "The Rogue"}, new int[]{65,68,70,62});
    	a[59] = new Entry("./res/rest_no_rogue_no_knight.png", "",  new String[]{"Click here to continue"}, new int[]{60});
        a[60] = new Entry("./res/rest_no_rogue_no_knight.png", "As the group is getting tired, you decide that it's a good idea to set up a camp just outside the town of Ironshade.\nBecause this area is known to be somewhat dangerous, you decide that someone must stay up and keep watch at all times. ",  new String[]{"Click here to Continue"}, new int[]{61});
        a[61] = new Entry("./res/rest_no_rogue_no_knight.png", "So everyone can sleep, you also decide that this will be done in shifts. The question is, who takes the first watch shift?",  new String[]{"You", "The Mage"}, new int[]{65,70});
    	a[62] = new Entry("./res/game_over.png", "Unbeknownst to everyone in the group, the Rogue had a band of thieves trailing along behind her...\nWhen she took watch, it was the perfect time for the band of thieves to ambush the group. They stole all the supplies and attacked the entire group.",  new String[]{"Click here to Continue"}, new int[]{63});
        a[63] = new Entry("./res/game_over.png", "Everyone was so badly injured in the attack that they could not continue the journey and had to turn back to Clearborrow. \nUnfortunately, this meant that the Princess never made it to Woodness and was never able to marry the Prince.\nYou felt like you should've seen that coming and listened to your gut feeling, but that wasn't the choice you made.",  new String[]{"Click here to Continue"}, new int[]{64});
        a[64] = new Entry("./res/game_over.png", "\"I believe in intuition and inspiration...I sometimes feel that I'm right, even though I do not know that I am.\"\n-Albert Einstein",  new String[]{"Go back to resting with Rogue", "Start over"}, new int[]{57,0});
        a[65] = new Entry("./res/everyone_happy.png", "",  new String[]{"Click here to continue"}, new int[]{66});
        a[66] = new Entry("./res/everyone_happy.png", "You take the watch for the evening, then trade places periodically with the other members of the group (except for the Princess, of course). Everyone is happy that they get a good night's rest.",  new String[]{"Click here to Continue"}, new int[]{67});
        a[67] = new Entry("./res/everyone_happy.png", "Some members of the group suggest that you should stop in the village and talk to some of the locals, possibly getting more supplies.\nYou contemplate these choices and need to decide on the next step for the group. What do you do?",  new String[]{"Stop, But Don't Talk to Anyone", "Stop and Talk to the Local Villagers", "Don't Stop, Keep Going Toward Woodness"}, new int[]{99,99,99});
    	a[68] = new Entry("./res/everyone_happy.png", "",  new String[]{"Click here to continue"}, new int[]{69});
        a[69] = new Entry("./res/everyone_happy.png", "The Knight takes the first watch, then trades places periodically with the other members of the group (except for the Princess, of course). Everyone is happy that they get a good night's rest. ",  new String[]{"Click here to Continue"}, new int[]{67});
        a[70] = new Entry("./res/mage_explosion.png", "",  new String[]{"Click here to continue"}, new int[]{71});
        a[71] = new Entry("./res/mage_explosion.png", "The Mage the first watch and decides to practice his magic a bit...\nThis leads to an accidental explosion. While shocking and loud, no one was hurt and the Mage apologizes. ",  new String[]{"Click here to Continue"}, new int[]{72});
        a[72] = new Entry("./res/mage_explosion.png", "Everyone doesn't get much sleep, but manages to wake up on time the next morning and press on.\nThis leads to an accidental explosion. While shocking and loud, no one was hurt and the Mage apologizes. ",  new String[]{"Click here to Continue"}, new int[]{73});
        a[73] = new Entry("./res/mage_explosion.png", "Some members of the group suggest that you should stop in the village of Ironshade and talk to some of the locals, possibly getting more supplies. \nYou contemplate these choices and need to decide on the next step for the group. What do you do?",  new String[]{"Stop, But Don't Talk to Anyone", "Stop and Talk to the Local Villagers", "Don't Stop, Keep Going Toward Woodness"}, new int[]{99,99,99});

    }

}